version: '3'
services:
  php_backend:
    container_name: 'challange_php'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
    ports:
      - 5000:80
    expose:
      - 80
    networks:
      - app_network
    labels:
      maintainer: 'zubair'
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: 'challange_database'
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'challange_pgadmin'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: zubair.mi45@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mynameismethos
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    ports:
      - 3000:80
    depends_on:
      - db
    networks:
      - app_network

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin: